#!/bin/bash

CI_NODE='ci-cpi-stub.dev.wh.reachlocal.com'
APP_DIR='/rl/product/cpi/cpi-gateway-service'
USER='appuser'
RVM='/var/people/appuser/.rvm/bin/rvm'
SET_RVM='echo "Setting up remote ruby environment..." && source ~/.rvm/environments/ruby-2.1.0@global && which ruby'
BUNDLE='~/.rvm/environments/ruby-2.1.0@global/bin/bundle'

function setup() {
  ssh ${USER}@${CI_NODE} "bash -s" <<LimitString
    cd /rl/product/cpi
    ${RVM} install 2.1.0
    ${SET_RVM}
    gem install bundler --no-rdoc --no-ri && which bundle && bundle --version
    if [ -d ${APP_DIR} ]; then
      cd ${APP_DIR} && git pull
    else
      git clone  ssh://git@stash.lax.reachlocal.com/cpi/cpi-gateway-service.git
    fi
    bundle
LimitString
}

function run() {
  echo 'Running the remote server...'
  ssh ${USER}@${CI_NODE} "bash -s" <<LimitString
    ${SET_RVM}
    cd ${APP_DIR}
    bundle
    SKIP_AUTH=1 STUB_SERVICES=1 nohup bundle exec rackup -p8001 > /dev/null 2>&1 &
    echo "\$!" > ${APP_DIR}/pid
LimitString
}

function refresh() {
  ssh ${USER}@${CI_NODE} "bash -s" <<LimitString
    ${SET_RVM}
    cd ${APP_DIR}
    git pull
    bundle
LimitString
}

function stop_server() {
  ssh ${USER}@${CI_NODE} "bash -s" <<LimitString
    ${SET_RVM}
    cd ${APP_DIR}
    cat ${APP_DIR}/pid | xargs kill -9
LimitString
}

function usage() {
  echo 'Usage: ./gateway <setup|run|stop>'
}

case "$1" in
  "run" ) run ;;
  "stop" ) stop_server ;;
  "refresh" ) refresh ;;
  "setup" ) setup ;;
  "usage" ) usage ;;
  *) usage ;;
esac
